config/routes.rb
Rails.application.routes.draw do
	root 'home#top'

  	devise_for :users
  	resources :comments
  	
  	get 'guests/show'

  	resources :divesites, only: [:index, :show] do
  		member do
  			get :like
  		end
  	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
	has_many :divesites, through: :classified_site
end

app/models/classified_site.rb
class ClassifiedSite < ApplicationRecord
	belongs_to :divesite
	belongs_to :experience
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :divesite
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/divesite.rb
class Divesite < ApplicationRecord
	has_many :classified_site
	has_many :experiences, through: :classified_site
	has_many :comments
	has_many :divesite_likes, dependent: :destroy
	belongs_to :area
	belongs_to :style
	belongs_to :level
	belongs_to :country

	# geocoded_by :address
	# after_validation :geocode

	scope :area_id_search, -> area_id { where(area_id: area_id) }
	# scope :site_search, -> { includes(:experiences).where("experiences.id = #{experience_1} OR experiences.id = #{experience_2}").references(:experiences) }

	def like_from?(user)
		self.divesite_likes.exists?(user_id: user.id)
	end
end

app/models/divesite_like.rb
class DivesiteLike < ApplicationRecord
	belongs_to :divesite
	belongs_to :user
end

app/models/experience.rb
class Experience < ApplicationRecord
	has_many :classified_site
	has_many :divesites, through: :classified_site
end

app/models/level.rb
class Level < ApplicationRecord
	has_many :diveites
end

app/models/style.rb
class Style < ApplicationRecord
	has_many :diveites
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :comments, dependent: :destroy
  has_many :divesite_likes, dependent: :destroy

  mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	add_flash_types :success, :info, :warning, :danger

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image])
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		@comment = Comment.new
	end

	def create
		# binding.pry
		comment = Comment.new(comment_params)
		if comment.save
			@divesite = Divesite.find(params[:comment][:divesite_id])
			redirect_to divesite_url(id: @divesite)
		else
			redirect_back(fallback_location: root_path)
		end 
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])
		@comment.update(comment_params)
		redirect_to guests_show_url(id: current_user.id)
	end

	def destroy
		comment = Comment.find(params[:id])
		comment.destroy
		redirect_to guests_show_url(id: current_user.id)
	end

	private

	def comment_params
		params.require(:comment).permit(:comment, :user_id, :divesite_id)
	end
end

app/controllers/divesites_controller.rb
class DivesitesController < ApplicationController

  def index
  	area = params[:fun_dive_search][:area_id]
  	experience_1 = params[:fun_dive_search][:experience_1]
  	experience_2 = params[:fun_dive_search][:experience_2]

    # flash message
    if area.empty? && experience_1.empty? && experience_2.empty?
      redirect_to root_url, warning: "Please choose area and at least one experience."
    elsif area.empty?
      redirect_to root_url, warning: "Please choose area." 
    elsif experience_1.empty? && experience_2.empty?
      redirect_to root_url, warning: "Please choose at least one experience." 
    end

# 以下の検索を、scopeでまとめたい
    # experienceが両方とも選択されている場合
  	if !experience_1.empty? && !experience_2.empty? # empty?の逆は !empty?
    		# @divesites = Divesite.where(area_id: params[:fun_dive_search][:area_id]).includes(:experiences).where("experiences.id = #{experience_1} OR experiences.id = #{experience_2}").references(:experiences)
        @divesites = Divesite.area_id_search(area).includes(:experiences).where("experiences.id = #{experience_1} OR experiences.id = #{experience_2}").references(:experiences)

  	else
      # experienceが片方のみ選択されてる場合
  		experience = []
  		experience << experience_1 unless experience_1.empty?
  		experience << experience_2 unless experience_2.empty?
  	  	# @divesites = Divesite.where(area_id: params[:fun_dive_search][:area_id]).includes(:experiences).where("experiences.id": experience[0]).references(:experiences)	
      @divesites = Divesite.area_id_search(area).includes(:experiences).where("experiences.id": experience[0]).references(:experiences)   

    end
    
    # ----------------
  	# ↓で検索可
  	# Divesite.first.classified_site
  	# Divesite.first.experiences
  	# @divesites = Divesite.where(area_id: 1).includes(:experiences).where("experiences.id": 1).references(:experiences)
    # ----------------

  end

  def show
    @divesite = Divesite.find(params[:id])
    @comments = Comment.where(divesite: params[:id])
  end

  def like
    @divesite = Divesite.find(params[:id])
    if DivesiteLike.exists?(divesite_id: @divesite.id, user_id: current_user.id)
      DivesiteLike.find_by(divesite_id: @divesite.id, user_id: current_user.id).destroy
      redirect_back(fallback_location: root_path)
    else
      DivesiteLike.create(divesite_id: @divesite.id, user_id: current_user.id)
      redirect_back(fallback_location: root_path)
    end
  end

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@comments = Comment.where(user_id: params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = 'DiveNuts'
		if page_title.empty?
			base_title
		else
			page_title + ' | ' + base_title
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/divesites_helper.rb
module DivesitesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<div class="detail" style="margin-top: 150px; margin-bottom: 200px">
	<p>Update a review</p>
	<div class="form">
		<%= form_for(@comment, url: comment_path, method: :patch, class: "comment_form") do |f| %>
			<div>
			<%= f.text_area :comment %>
			</div>
			<%= f.submit "Update Review" %>
		<% end -%>
	</div>
</div>

app/views/divesites/index.html.erb
<% provide(:title, "Choose a site") %>

<div class="divesite-list-content">
	<% if @divesites.any? %>
	<div class="list-title">
		<div class="list-title-contents">
			<h2><%= @divesites.first.area.name %></h2>
			<p>Total <%= @divesites.count%> sites</p>
		</div>
	</div>

	<% @divesites.each do |site| %>
	<div class="divesite-container">
		<div class="divesite-list">
			<div class="divesite-list-info">
				<tr>
					<th><%= site.name %></th>
					<br>
					<th><%= site.country.name %></th>
					<br><br>
					<th>
						<%= link_to '>>> See details', divesite_path(id: site) %>
					</th>
				</tr>
			</div>
			<div class="divesite-list-map">
				<iframe src="https://www.google.com/maps?q=<%= site.lat %>,<%= site.long %>&output=embed&z=10" width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen></iframe>
			</div>
		</div>
	</div>
	<hr class="divesite-list-hr">
	<% end -%>
	<% else %>
		<div class="list-title">
			<div class="list-title-contents">
				<h4 style="line-height: 30px">Sorry, there is no divesites that match your selection.<br>
				Please try with different options.</h4>
				<div class="align-buttons">
					<%= link_to "Top Page", root_path %>
				</div>
			</div>
		</div>
	<% end -%>
</div>

app/views/divesites/show.html.erb
<% provide(:title, "Divesite") %>

<div class="divesite">
	<div class="divesite-titles">
		<div class="slider-container">
			<ul class="slider">
				<li><img class="img" src="<%= @divesite.image_1 %>"></li>
				<li><img class="img" src="<%= @divesite.image_2 %>"></li>
				<li><img class="img" src="<%= @divesite.image_3 %>"></li>
			</ul>
		</div>
		<p class="divesite-name"><%= @divesite.name %></p>
		<hr class="details" style="margin-top: -1px">
		<p class="divesite-country"><%= @divesite.country.name %></p>
	</div>
	<div class="divesite-details">
		<div class="detail">

			<p class="divesite-info">Dive site information of <b><%= @divesite.name %></b></p>
			<% if user_signed_in? %>
				<%= link_to like_divesite_path(@divesite) do %>
				  <i class="fa <%= @divesite.like_from?(current_user)? "fa-heart active" : "fa-heart-o" %> fa-2x"></i><!-- いいねを押してない時 -->
				<% end %>
			<% end -%>
			<hr class="details" style="clear: both;">
			<ul class="divesite-description">
				<li>Country: &nbsp;&nbsp;&nbsp;<%= @divesite.country.name %></li>
				<li>Level: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @divesite.level.name %></li>
				<li>Style: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @divesite.style.name %></li>
				<li>Best season: &nbsp;&nbsp;&nbsp;<%= @divesite.season %></li>
				<li>Site description:<br><br> <%= @divesite.feature %></li>
			</ul>
		</div>

		<% if user_signed_in? %>
		<div class="detail">
			<p>Leave a review</p>
			<p class="notification">Please leave a review in case you have been to this site for diving</p>
			<div class="form">
				<%= form_for(Comment.new, url: comments_path, method: :post, class: "comment_form") do |f| %>
					<div>
					<%= f.text_area :comment %>
					<%= f.hidden_field :user_id, value: current_user.id %>
					<%= f.hidden_field :divesite_id, value: @divesite.id %>
					</div>
					<%= f.submit "Post Review", class: 'submit_button' %>
				<% end -%>
			</div>
		</div>
		<% end -%>
		<div class="detail-comments">
			<div class="detail">
				<p>Comments by users who've been to this site</p>
				<hr class="details">
				<% if @comments.any? %>
					<% @comments.each do |comment| %>
						<div class="comments">
							<div>
								<%= image_tag comment.user.image.url(:thumb), class: 'thumb_img' %>
								<%= comment.user.name %><span class="date"><%= comment.updated_at.strftime('%Y/%m/%d') %></span>
							</div>
							<p><%= comment.comment %></p>
						</div>
					<% end -%>
					<% else %>
						<p class="notification">There is no reviews at this moment.</p>
				<% end -%>
			</div>
			<div class="users-divesites">
				<p class="users-divesites-button">Check out nearby dive sites recommended by other users &nbsp;<i class="fa fa-chevron-circle-down"></i></p>
			</div>
		</div>

		<div class="users-divesites-container">
			<div class="users-divesites-contents">
				<p>Recommended dive sites nearby <b><%= @divesite.name %></b></p>
				<hr class="details">
				<p><%= Divesite.first.name %></p>
				<ul class="divesite-description">
					<li>Country: &nbsp;&nbsp;&nbsp;<%= Divesite.first.country.name %></li>
					<li>Level: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= Divesite.first.level.name %></li>
					<li>Style: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= Divesite.first.style.name %></li>
					<li>Best season: &nbsp;&nbsp;&nbsp;<%= Divesite.first.season %></li>
				</ul>
				<hr class="details">
			</div>
		</div>
		<% unless user_signed_in? %>
			<div class="registration">
				<div class="sign-up-content-show">
					<p>You can post reviews to your favorite dive sites and help us to build dive site API after signing up with DiveNuts. <br><br> 
					TO GET MORE EXPERIENCE WITH US</p>
					<%= link_to 'Sign Up', new_user_registration_path %>
				</div>
			</div>
		<% end -%>
	</div>
</div>

app/views/guests/show.html.erb
<% provide(:title, "My Account") %>

<div class="divesite-list-content">
	<div class="list-title">
		<div class="list-title-contents">
			<h2>Welcome <%= @user.name %>!</h2>
		</div>
	</div>
	<div class="detail" style="margin-top: 80px">
		<p>My Profile</p>
		<hr class="details">
		<%= image_tag @user.image.url, class: 'my_image' %>

		<ul class="divesite-description">
			<li>Username: &nbsp;&nbsp;&nbsp; <%= @user.name%></li>
			<li>Email: &nbsp;&nbsp;&nbsp; <%= @user.email%></li>
		</ul>
		<div class="user_button"><%= link_to "Update Your Profile", edit_user_registration_path %></div>
	</div>
	<div class="detail">
		<p>Posted Reviews</p>
		<hr class="details">
		<% if @comments.any? %>
		<ul class="divesite-description">
			<% @comments.each do |comment| %>
				<li style="line-height: 25px"><u><%= link_to "#{comment.comment.truncate(50)} ( #{comment.divesite.name} )", divesite_path(id: comment.divesite_id) %></u> <span style="padding-left: 25px" class="review_update_button"><%= link_to "Edit", edit_comment_path(comment) %> <%= link_to "Delete", comment_path(comment), method: :delete %></span>
				</li>
			<% end -%>
		</ul>
		<% else %>
			<p class="notification">You don't have reviews</p>
		<% end -%>
	</div>
	<div class="detail">
		<p>Divesite Recommendations</p>
		<hr class="details">
		<ul class="divesite-description">
			<li>Username: &nbsp;&nbsp;&nbsp; <%= @user.name%></li>
			<li>Email: &nbsp;&nbsp;&nbsp; <%= @user.email%></li>
		</ul>
	</div>

</div>

app/views/home/_area-select.html.erb
<%= form_for :divesite, url: 'divesites/map', method: :post do |f| %>
	<%= f.collection_select :area_id, Area.all, :id, :name, prompt: "Choose Area" %>

app/views/home/top.html.erb
<% provide(:title, "Top") %>
<div class="top">
	<div class="top-image">
		<div class="top-welcome">
			<h2>Welcome to DiveNuts</h2>
			<hr>
			<div style="float: right;">
				<p>Ready to discover a perfect dive site for your next trip?</p>
				<br>
				<p>We will help you to find the best destination with a fabulous experience.</p>
			</div>
		</div>
	</div>
</div>
<div class="about">
	<p>We will help scuba divers to choose their perfect next dive sites based on your prefferred location and features. This is more gaming style app, so feel free to enjoy and discover unexpected dive sites that match your desire.<br><br>
                        Only exceptional fun dive sites from all around the world will be shown you.
                        Please join us through signing up, so you can enjoy DiveNuts much more. </p>
    <h3>Let's get started finding your next destination!</h3>
    <a href="#primary-questions"><i class="fa fa-angle-double-down fa-2x"></i></a>
</div>

<div id="primary-questions">
	<div class="primary-questions-area">
		<p>Are you looking for next dive site for ..</p>
		<hr class="details">
		<div class="align-buttons">
			<a href="" id="beginners">Fun Seekers</a>
			<a href="" id="advanced">Advanced Divers</a>
		</div>
	</div>
</div>

<div id="for-fun-seakers">
	<div id="area-map">
		<div class="area-select">
			<h3>1. Which area would you like to dive?</h3>
			<p>Choose one area you wish to dive from below button.</p>
			<!-- f.collection_select <属性名>, <表示させるモデル>, <渡す値>, <モデルから表示させるカラム>, prompt: <デフォルト表示文字> -->
			<%= form_for :fun_dive_search, url: divesites_path, method: :get do |f| %>
				<%= f.collection_select :area_id, Area.all, :id, :name, prompt: "Choose Area" %>
			<p class="googlemaps"><a href="https://www.google.com/maps"> >> Check areas on map</a></p>
		</div>
	</div>
	<div id="experience">
		<div class="experience-select">
			<h3>2. What would you expect?</h3>
			<p>Choose up to two experiences you wish for next diving.</p>
			<div class="select-buttons">
				<p>1st select &nbsp;&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></p>
				<%= f.collection_select :experience_1, Experience.all, :id, :name, prompt: "Choose Experience" %><br><br>
				<p>2nd select &nbsp;<i class="fa fa-arrow-circle-right"></i></p>
				<%= f.collection_select :experience_2, Experience.all, :id, :name, prompt: "Choose Experience" %>
			</div>
			&nbsp;&nbsp;&nbsp;&nbsp;
			<%= f.submit 'Check Out Divesites', class: 'submit' %>
		<% end -%>
		</div>
	</div>
</div>

<div id="for-advanced-divers">
	<div id="area-map">
		<div class="area-select">
			<h3>Coming Soon</h3>
		</div>
	</div>
	<div id="experience">
		<div class="experience-select">
			<h3>Coming Soon</h3>
		</div>
	</div>
</div>

<div id="sign-up">
	<div class="sign-up-content">
		<% if user_signed_in? %>
			<p>Build DiveNuts API with us ! Tell me your recommended dive sites.</p>
			<%= link_to 'Build DiveNuts API', guests_show_path(id: current_user.id) %>
		<% else %>
			<p>Sign up now and enjoy more scuba diving with DiveNuts !</p>
			<%= link_to 'Sign Up', new_user_registration_path %>
		<% end -%>
	</div>
</div>